### ISSUE TITLE
Is there any result of your code?

### ISSUE THREAD

**Issue by lipanpeng** [GIMPS/gan_lf_syn#1]
I am interested in View Synthesis by Appearance Flow and I am glad to find your implementation with python. Have you gotten good results?

**Comment by GIMPS** [comment]
Thanks for your interest. The repo is still WIP. I am right now training on full dataset. It may take a few days. I will update once I get the result.

**Comment by lipanpeng** [comment]
OK. I implemented with tensorflow. But I got meaningless results, all pixels grey. I don't know what's wrong.

**Comment by GIMPS** [comment]
Not sure what is the problem in your implementation. I have encountered something similar. It turned out that the problem was with the method `im2double`.  After `im2double`, the pixel value will NOT remain as a integer from 0-255. You may need to restore the pixel value if you want to `imwrite` directly with opencv.

**Comment by GIMPS** [comment]
Results updated.
